DROP TRIGGER IF EXISTS cekNoHP;
DELIMITER &&
CREATE TRIGGER cekNoHP BEFORE INSERT ON t_identitas
FOR EACH ROW
BEGIN
	DECLARE noHP VARCHAR(15);
	SET noHP = NEW.nohp;
	IF (LEFT(noHP, 1) = "0") THEN
		SET NEW.nohp = CONCAT('62', MID(noHP,2,LENGTH(noHP)-1));
	END IF;
END
&&
DELIMITER;